from tensorflow_tts.configs.fastspeech import FastSpeechConfig

from tensorflow_tts.configs.fastspeech2 import FastSpeech2Config

from tensorflow_tts.configs.melgan import MelGANGeneratorConfig
from tensorflow_tts.configs.melgan import MelGANDiscriminatorConfig

from tensorflow_tts.configs.tacotron2 import Tacotron2Config

from tensorflow_tts.configs.mb_melgan import MultiBandMelGANGeneratorConfig
from tensorflow_tts.configs.mb_melgan import MultiBandMelGANDiscriminatorConfig
