from tensorflow_tts.processor.base_processor import BaseProcessor

from tensorflow_tts.processor.ljspeech import LJSpeechProcessor
from tensorflow_tts.processor.baker import BakerProcessor
from tensorflow_tts.processor.kss import KSSProcessor
from tensorflow_tts.processor.libritts import LibriTTSProcessor
from tensorflow_tts.processor.thorsten import ThorstenProcessor
from tensorflow_tts.processor.ljspeechu import LJSpeechUltimateProcessor
from tensorflow_tts.processor.synpaflex import SynpaflexProcessor
from tensorflow_tts.processor.jsut import JSUTProcessor
